#!/bin/sh
set -eu

PROGRAM_NAME=${0##*/}
REALITYCHAIN_HOME=${REALITYCHAIN_HOME:-/jffs/addons/realitychain}
INIT_SCRIPT=${REALITYCHAIN_INIT_SCRIPT:-/opt/etc/init.d/S99realitychain}
ENV_FILE=${REALITYCHAIN_ENV_FILE:-$REALITYCHAIN_HOME/client.env}
POLICY_FILE=${REALITYCHAIN_POLICY_FILE:-$REALITYCHAIN_HOME/policy.json}
PAGE_SRC=${REALITYCHAIN_WEBUI_PAGE:-$REALITYCHAIN_HOME/webui/RealityChain.asp}
SETTINGS_FILE=/jffs/addons/custom_settings.txt
PID_FILE=/var/run/realitychain-xray.pid

log() {
	if command -v logger >/dev/null 2>&1; then
		logger -t RealityChain "$*"
	else
		printf '%s\n' "$*" >&2
	fi
}

die() {
	log "$*"
	exit 1
}

load_helper() {
	[ -f /usr/sbin/helper.sh ] || die "Merlin addon helper not found"
	# shellcheck disable=SC1091
	. /usr/sbin/helper.sh
}

setting_exists() {
	[ -f "$SETTINGS_FILE" ] && grep -q "^$1 " "$SETTINGS_FILE"
}

setting_get() {
	am_settings_get "$1" 2>/dev/null || true
}

setting_get_or() {
	key=$1
	fallback=$2

	if setting_exists "$key"; then
		setting_get "$key"
	else
		printf '%s' "$fallback"
	fi
}

setting_set_if_missing() {
	key=$1
	value=$2

	if ! setting_exists "$key"; then
		am_settings_set "$key" "$value"
	fi
}

clean_value() {
	printf '%s' "$1" | tr -d '\r\n'
}

quote_env_value() {
	printf "'"
	printf '%s' "$1" | sed "s/'/'\\\\''/g"
	printf "'"
}

write_env_line() {
	key=$1
	value=$2

	printf '%s=' "$key"
	quote_env_value "$value"
	printf '\n'
}

load_existing_env() {
	if [ -f "$ENV_FILE" ]; then
		# shellcheck disable=SC1090
		. "$ENV_FILE"
	fi
}

import_env_to_settings() {
	load_helper
	load_existing_env

	setting_set_if_missing rch_enabled "1"
	setting_set_if_missing rch_server_address "${SERVER_ADDRESS:-vpn.example.net}"
	setting_set_if_missing rch_server_port "${SERVER_PORT:-443}"
	setting_set_if_missing rch_vless_uuid "${VLESS_UUID:-00000000-0000-4000-8000-000000000000}"
	setting_set_if_missing rch_reality_public_key "${REALITY_PUBLIC_KEY:-}"
	setting_set_if_missing rch_reality_short_id "${REALITY_SHORT_ID:-}"
	setting_set_if_missing rch_reality_server_name "${REALITY_SERVER_NAME:-www.microsoft.com}"
	setting_set_if_missing rch_reality_fingerprint "${REALITY_FINGERPRINT:-chrome}"
	setting_set_if_missing rch_ks_enabled "${KILLSWITCH_ENABLED:-1}"
	setting_set_if_missing rch_ks_interval "${KILLSWITCH_WATCH_INTERVAL:-10}"
	setting_set_if_missing rch_anchor_rpc_url "${ANCHOR_RPC_URL:-}"
	setting_set_if_missing rch_anchor_contract "${ANCHOR_CONTRACT:-}"
	setting_set_if_missing rch_anchor_storage_slot "${ANCHOR_STORAGE_SLOT:-}"
	setting_set_if_missing rch_policy_file "${POLICY_FILE:-$POLICY_FILE}"
	update_status "imported"
}

sync_settings_to_env() {
	load_helper
	load_existing_env

	server_address=$(clean_value "$(setting_get_or rch_server_address "${SERVER_ADDRESS:-vpn.example.net}")")
	server_port=$(clean_value "$(setting_get_or rch_server_port "${SERVER_PORT:-443}")")
	vless_uuid=$(clean_value "$(setting_get_or rch_vless_uuid "${VLESS_UUID:-00000000-0000-4000-8000-000000000000}")")
	reality_public_key=$(clean_value "$(setting_get_or rch_reality_public_key "${REALITY_PUBLIC_KEY:-}")")
	reality_short_id=$(clean_value "$(setting_get_or rch_reality_short_id "${REALITY_SHORT_ID:-}")")
	reality_server_name=$(clean_value "$(setting_get_or rch_reality_server_name "${REALITY_SERVER_NAME:-www.microsoft.com}")")
	reality_fingerprint=$(clean_value "$(setting_get_or rch_reality_fingerprint "${REALITY_FINGERPRINT:-chrome}")")
	killswitch_enabled=$(clean_value "$(setting_get_or rch_ks_enabled "${KILLSWITCH_ENABLED:-1}")")
	killswitch_interval=$(clean_value "$(setting_get_or rch_ks_interval "${KILLSWITCH_WATCH_INTERVAL:-10}")")
	anchor_rpc_url=$(clean_value "$(setting_get_or rch_anchor_rpc_url "${ANCHOR_RPC_URL:-}")")
	anchor_contract=$(clean_value "$(setting_get_or rch_anchor_contract "${ANCHOR_CONTRACT:-}")")
	anchor_storage_slot=$(clean_value "$(setting_get_or rch_anchor_storage_slot "${ANCHOR_STORAGE_SLOT:-}")")
	policy_file=$(clean_value "$(setting_get_or rch_policy_file "${POLICY_FILE:-$POLICY_FILE}")")

	tmp_file=$ENV_FILE.$$
	{
		printf '# Generated by RealityChain WebUI. Manual edits may be overwritten.\n'
		write_env_line SERVER_ADDRESS "$server_address"
		write_env_line SERVER_PORT "$server_port"
		write_env_line SERVER_LISTEN "${SERVER_LISTEN:-0.0.0.0}"
		write_env_line VLESS_UUID "$vless_uuid"
		write_env_line REALITY_PUBLIC_KEY "$reality_public_key"
		write_env_line REALITY_PRIVATE_KEY "${REALITY_PRIVATE_KEY:-}"
		write_env_line REALITY_SHORT_ID "$reality_short_id"
		write_env_line REALITY_SERVER_NAME "$reality_server_name"
		write_env_line REALITY_DEST "${REALITY_DEST:-$reality_server_name:443}"
		write_env_line REALITY_FINGERPRINT "$reality_fingerprint"
		write_env_line LAN_IFACE "${LAN_IFACE:-br0}"
		write_env_line LOCAL_TPROXY_PORT "${LOCAL_TPROXY_PORT:-12345}"
		write_env_line KILLSWITCH_ENABLED "$killswitch_enabled"
		write_env_line KILLSWITCH_WATCH_INTERVAL "$killswitch_interval"
		write_env_line KILLSWITCH_REJECT_WITH "${KILLSWITCH_REJECT_WITH:-icmp-port-unreachable}"
		write_env_line ANCHOR_RPC_URL "$anchor_rpc_url"
		write_env_line ANCHOR_CONTRACT "$anchor_contract"
		write_env_line ANCHOR_STORAGE_SLOT "$anchor_storage_slot"
		write_env_line POLICY_FILE "$policy_file"
	} >"$tmp_file"
	mv "$tmp_file" "$ENV_FILE"
	chmod 0600 "$ENV_FILE"
}

update_status() {
	anchor_status=${1:-not_checked}
	load_helper

	if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" >/dev/null 2>&1; then
		status=running
	else
		status=stopped
	fi

	policy_path=$(setting_get_or rch_policy_file "$POLICY_FILE")
	if [ -x "$REALITYCHAIN_HOME/realitychainctl" ] && [ -f "$policy_path" ]; then
		policy_hash=$("$REALITYCHAIN_HOME/realitychainctl" policy-hash "$policy_path" 2>/dev/null || printf 'unavailable')
	else
		policy_hash=unavailable
	fi

	if [ -x "$REALITYCHAIN_HOME/realitychain-killswitch.sh" ] && [ -f "$ENV_FILE" ]; then
		ks_state=$("$REALITYCHAIN_HOME/realitychain-killswitch.sh" status "$ENV_FILE" 2>/dev/null || printf 'unknown')
	else
		ks_state=unknown
	fi

	am_settings_set rch_status "$status"
	am_settings_set rch_anchor_status "$anchor_status"
	am_settings_set rch_policy_hash "$policy_hash"
	am_settings_set rch_ks_state "$ks_state"
	am_settings_set rch_updated_at "$(date '+%Y-%m-%d %H:%M:%S %Z' 2>/dev/null || date)"
}

mount_webui() {
	load_helper

	if ! nvram get rc_support 2>/dev/null | grep -q am_addons; then
		die "firmware does not advertise am_addons support"
	fi

	[ -f "$PAGE_SRC" ] || die "WebUI page not found: $PAGE_SRC"
	[ -d /www/user ] || die "Merlin WebUI user directory not found"

	stored_page=$(setting_get rch_webui_page)
	case "$stored_page" in
		user*.asp)
			am_webui_page=$stored_page
			;;
		*)
			am_get_webui_page "$PAGE_SRC"
			;;
	esac
	[ "$am_webui_page" != "none" ] || die "no available Merlin custom WebUI page slot"

	cp "$PAGE_SRC" "/www/user/$am_webui_page"
	am_settings_set rch_webui_page "$am_webui_page"

	if [ ! -f /tmp/menuTree.js ]; then
		cp /www/require/modules/menuTree.js /tmp/menuTree.js
	fi

	if grep -q 'tabName: "RealityChain"' /tmp/menuTree.js; then
		sed -i "s/{url: \"user[0-9][0-9]*.asp\", tabName: \"RealityChain\"}/{url: \"$am_webui_page\", tabName: \"RealityChain\"}/" /tmp/menuTree.js
	else
		sed -i "/url: \"Tools_OtherSettings.asp\", tabName:/a {url: \"$am_webui_page\", tabName: \"RealityChain\"}," /tmp/menuTree.js
	fi

	umount /www/require/modules/menuTree.js >/dev/null 2>&1 || true
	mount -o bind /tmp/menuTree.js /www/require/modules/menuTree.js
	log "mounted WebUI page as $am_webui_page"
}

restart_service() {
	sync_settings_to_env
	load_helper

	if [ "$(setting_get_or rch_enabled 1)" = "0" ]; then
		"$INIT_SCRIPT" stop >/tmp/realitychain-webui-action.log 2>&1 || true
		update_status disabled
		return
	fi

	if "$INIT_SCRIPT" restart >/tmp/realitychain-webui-action.log 2>&1; then
		update_status verified_or_disabled
	else
		update_status failed
		die "failed to restart RealityChain; see /tmp/realitychain-webui-action.log"
	fi
}

stop_service() {
	load_helper
	am_settings_set rch_enabled 0
	"$INIT_SCRIPT" stop >/tmp/realitychain-webui-action.log 2>&1 || true
	update_status stopped
}

engage_killswitch() {
	sync_settings_to_env
	load_helper
	"$REALITYCHAIN_HOME/realitychain-killswitch.sh" engage "$ENV_FILE" >/tmp/realitychain-webui-action.log 2>&1 || true
	update_status manual_killswitch
}

clear_killswitch() {
	sync_settings_to_env
	load_helper
	"$REALITYCHAIN_HOME/realitychain-killswitch.sh" clear "$ENV_FILE" >/tmp/realitychain-webui-action.log 2>&1 || true
	update_status manual_clear
}

service_event() {
	type=${1:-}
	event=${2:-}

	case "$event:$type" in
		realitychain:start|realitychain:restart)
			restart_service
			;;
		realitychain:stop)
			stop_service
			;;
		realitychainks:start)
			engage_killswitch
			;;
		realitychainks:stop)
			clear_killswitch
			;;
	esac
}

case "${1:-}" in
	mount)
		mount_webui
		;;
	import-env)
		import_env_to_settings
		;;
	sync)
		sync_settings_to_env
		;;
	status)
		update_status "${2:-manual}"
		;;
	service-event)
		shift
		service_event "$@"
		;;
	*)
		printf 'Usage: %s {mount|import-env|sync|status|service-event TYPE EVENT}\n' "$PROGRAM_NAME" >&2
		exit 2
		;;
esac
